# Generated by Django 6.0.6 on 2026-07-02 15:10

import catalog.models
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_item_options_item_image_alter_item_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('150.00'), max_digits=10, validators=[catalog.models.validate_strictly_150]),
        ),
    ]
